//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseArea
    {
        public int Id { get; set; }
        public string AreaName { get; set; }
        public Nullable<bool> LightsOn { get; set; }
        public Nullable<bool> FloorHeating { get; set; }
        public Nullable<bool> Alarm { get; set; }
    }
}
